/*
 * Copyright (c) 2010-2026 Contributors to the openHAB project
 *
 * See the NOTICE file(s) distributed with this work for additional
 * information.
 *
 * This program and the accompanying materials are made available under the
 * terms of the Eclipse Public License 2.0 which is available at
 * http://www.eclipse.org/legal/epl-2.0
 *
 * SPDX-License-Identifier: EPL-2.0
 */
package org.openhab.binding.kseniasecurity.internal.state;

import java.util.EnumMap;
import java.util.Map;

import org.eclipse.jdt.annotation.NonNullByDefault;
import org.eclipse.jdt.annotation.Nullable;

/**
 * The current best-known state for one alarm zone.
 *
 * <p>
 * A field absent from {@link #values()} has not been supplied since the bridge started. Child handlers consume the
 * typed accessors rather than Lares wire values.
 *
 * @author Michele Pattera - Initial contribution
 */
@NonNullByDefault
public record ZoneSnapshot(int id, Map<ZoneStateField, String> values) {

    /**
     * Creates a snapshot with an immutable field map.
     *
     * @param id the panel zone identifier
     * @param values the known values, indexed by their semantic field
     */
    public ZoneSnapshot {
        values = Map.copyOf(values);
    }

    /**
     * Creates an empty snapshot for a zone that has not yet reported any fields.
     *
     * @param id the panel zone identifier
     * @return the initial snapshot
     */
    public static ZoneSnapshot initial(int id) {
        return new ZoneSnapshot(id, Map.of());
    }

    /**
     * Returns a new snapshot with the fields supplied in {@code update} applied.
     *
     * @param update the partial update to apply
     * @return the merged snapshot
     */
    public ZoneSnapshot merge(ZoneStateUpdate update) {
        if (id != update.id()) {
            throw new IllegalArgumentException("Cannot merge a state update for a different zone");
        }

        Map<ZoneStateField, String> mergedValues = new EnumMap<>(ZoneStateField.class);
        mergedValues.putAll(values);
        for (ZoneStateField clearedField : update.clearedFields()) {
            mergedValues.remove(clearedField);
        }
        mergedValues.putAll(update.values());
        return new ZoneSnapshot(id, mergedValues);
    }

    /**
     * Returns a known value for a field, if the panel has supplied it.
     *
     * @param field the semantic field to look up
     * @return the known value, or {@code null} when it is not known yet
     */
    public @Nullable String get(ZoneStateField field) {
        return values.get(field);
    }

    /**
     * Returns the current zone condition.
     *
     * @return the condition, or {@code null} when it has not been reported yet
     */
    public @Nullable ZoneCondition condition() {
        return getEnum(ZoneStateField.REALTIME_STATE, ZoneCondition.class);
    }

    /**
     * Returns the current zone bypass mode.
     *
     * @return the bypass mode, or {@code null} when it has not been reported yet
     */
    public @Nullable ZoneBypassMode bypassMode() {
        return getEnum(ZoneStateField.BYPASS_STATE, ZoneBypassMode.class);
    }

    /**
     * Returns the zone tamper event and memory state generated by the panel.
     *
     * @return the tamper cycle state, or {@code null} when it has not been reported yet
     */
    public @Nullable ZoneCycleState tamperCycleState() {
        return getEnum(ZoneStateField.TAMPER_STATE, ZoneCycleState.class);
    }

    /**
     * Returns the zone alarm event and memory state generated by the panel.
     *
     * @return the alarm cycle state, or {@code null} when it has not been reported yet
     */
    public @Nullable ZoneCycleState alarmCycleState() {
        return getEnum(ZoneStateField.ALARM_STATE, ZoneCycleState.class);
    }

    /**
     * Returns the fault-memory state reported for the zone.
     *
     * @return the fault-memory state, or {@code null} when it has not been reported yet
     */
    public @Nullable ZoneFaultState faultState() {
        return getEnum(ZoneStateField.FAULT_STATE, ZoneFaultState.class);
    }

    private <T extends Enum<T>> @Nullable T getEnum(ZoneStateField field, Class<T> type) {
        @Nullable
        String value = get(field);
        if (value == null) {
            return null;
        }

        try {
            return Enum.valueOf(type, value);
        } catch (IllegalArgumentException e) {
            return null;
        }
    }
}
