/*
 * Copyright (c) 2010-2026 Contributors to the openHAB project
 *
 * See the NOTICE file(s) distributed with this work for additional
 * information.
 *
 * This program and the accompanying materials are made available under the
 * terms of the Eclipse Public License 2.0 which is available at
 * http://www.eclipse.org/legal/epl-2.0
 *
 * SPDX-License-Identifier: EPL-2.0
 */
package org.openhab.binding.kseniasecurity.internal;

import org.eclipse.jdt.annotation.NonNullByDefault;
import org.openhab.core.thing.ThingTypeUID;

/**
 * Defines Thing type and channel identifiers used across the binding.
 *
 * @author Michele Pattera - Initial contribution
 */
@NonNullByDefault
public final class KseniaBindingConstants {

    public static final String BINDING_ID = "kseniasecurity";
    public static final String CONFIGURATION_PID = "binding." + BINDING_ID;

    public static final ThingTypeUID THING_TYPE_PANEL = new ThingTypeUID(BINDING_ID, "panel");
    public static final ThingTypeUID THING_TYPE_PARTITION = new ThingTypeUID(BINDING_ID, "partition");
    public static final ThingTypeUID THING_TYPE_ZONE = new ThingTypeUID(BINDING_ID, "zone");

    public static final String CHANNEL_PANEL_SYSTEM_LANG = "systemLang";
    public static final String CHANNEL_PANEL_SESSION_STATE = "sessionState";
    public static final String CHANNEL_PANEL_FREEZE_STATE = "freezeState";
    public static final String CHANNEL_PANEL_FW_VERSION = "firmwareVersion";
    public static final String CHANNEL_PANEL_WS_VERSION = "webserverVersion";
    public static final String CHANNEL_PANEL_DIAGNOSTIC_READ = "diagnosticRead";

    public static final String CHANNEL_PARTITION_DESCRIPTION = "description";
    public static final String CHANNEL_PARTITION_REALTIME_STATE = "realtimeState";
    public static final String CHANNEL_PARTITION_ARM_STATUS = "armStatus";
    public static final String CHANNEL_PARTITION_ENTRY_DELAY_STATUS = "entryDelayStatus";
    public static final String CHANNEL_PARTITION_EXIT_DELAY_STATUS = "exitDelayStatus";
    public static final String CHANNEL_PARTITION_DELAY_REMAINING = "delayRemaining";
    public static final String CHANNEL_PARTITION_ALARM_STATE = "alarmState";
    public static final String CHANNEL_PARTITION_ALARM_ACTIVE = "alarmActive";
    public static final String CHANNEL_PARTITION_ALARM_MEMORY = "alarmMemory";
    public static final String CHANNEL_PARTITION_TAMPER_STATE = "tamperState";
    public static final String CHANNEL_PARTITION_TAMPER_ACTIVE = "tamperActive";
    public static final String CHANNEL_PARTITION_TAMPER_MEMORY = "tamperMemory";

    public static final String CHANNEL_ZONE_DESCRIPTION = "description";
    public static final String CHANNEL_ZONE_REALTIME_STATE = "realtimeState";
    public static final String CHANNEL_ZONE_REST_STATUS = "restStatus";
    /** Current raw alarm condition reported in the zone {@code STA} field. */
    public static final String CHANNEL_ZONE_ALARM_STATUS = "alarmStatus";
    public static final String CHANNEL_ZONE_FAULT_STATUS = "faultStatus";
    public static final String CHANNEL_ZONE_TAMPER_STATUS = "tamperStatus";
    public static final String CHANNEL_ZONE_ERROR_STATUS = "errorStatus";
    public static final String CHANNEL_ZONE_BYPASS_STATE = "bypassState";
    public static final String CHANNEL_ZONE_BYPASS_STATUS = "bypassStatus";
    public static final String CHANNEL_ZONE_ALARM_STATE = "alarmState";
    /** Active alarm event generated by the panel, reported in the zone {@code A} field. */
    public static final String CHANNEL_ZONE_ALARM_ACTIVE = "alarmActive";
    public static final String CHANNEL_ZONE_ALARM_MEMORY = "alarmMemory";
    public static final String CHANNEL_ZONE_TAMPER_STATE = "tamperState";
    /** Active tamper event generated by the panel, reported in the zone {@code T} field. */
    public static final String CHANNEL_ZONE_TAMPER_ACTIVE = "tamperActive";
    public static final String CHANNEL_ZONE_TAMPER_MEMORY = "tamperMemory";
    public static final String CHANNEL_ZONE_FAULT_STATE = "faultState";
    public static final String CHANNEL_ZONE_FAULT_MEMORY = "faultMemory";

    private KseniaBindingConstants() {
    }
}
